import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const SUPABASE_URL='https://amjcrvanvqyuvqechkea.supabase.co';
const SUPABASE_KEY='sb_publishable_TKErdVlKvrjGYY___5OGeg_lq1ppXSi';
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY);
const channel=supabase.channel('aerion-outpost-v5',{config:{presence:{key:crypto.randomUUID()}}});
const el=id=>document.getElementById(id);
const keys=new Set();
let connected=false;
const players=new Map();
const enemies=[];
const clock=new THREE.Clock();
let scene,camera,renderer,hero,heroRoot,boss,portal;
let walkTime=0,attackUntil=0,sprinting=false;
let state=load();
function load(){const f={name:'Wanderer',race:'Human',world:'Aerion',role:'Unchosen',title:'Unmarked',level:1,xp:0,req:100,hp:100,st:100,coins:100,kills:0,deaths:0,authority:0,weather:'Clear',choiceDone:false,portalSeen:false,inventory:['Traveler Blade','Field Ration x3','Unknown Fragment'],attrs:{str:5,agi:5,vit:5,int:5,per:5,wil:5}};try{return {...f,...JSON.parse(localStorage.getItem('transcendence-v05')||'null'),attrs:{...f.attrs,...(JSON.parse(localStorage.getItem('transcendence-v05')||'null')?.attrs||{})}}}catch{return f}}
function save(){localStorage.setItem('transcendence-v05',JSON.stringify(state))}
function toast(t){el('toast').textContent=t;el('toast').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el('toast').classList.remove('show'),1700)}
function stage(){if(state.level>=999)return'DEMIGOD';if(state.level>=700)return'EXALTED';if(state.level>=450)return'SAINT';return'MORTAL'}
function xp(n){state.xp+=n;while(state.xp>=state.req){state.xp-=state.req;state.level++;state.req=Math.round(state.req*1.2);state.attrs.str++;state.attrs.vit++;if(state.level%2===0)state.attrs.agi++;toast('SYSTEM // LEVEL '+state.level)}save();ui()}
function ui(){el('worldPill').textContent=state.world.toUpperCase()+' // '+(state.world==='Aerion'?'OUTPOST':'ASHFALL');el('stagePill').textContent=stage()+' · LV '+state.level;el('onlinePill').textContent=connected?'ONLINE':'LOCAL';el('hpBar').style.width=state.hp+'%';el('stBar').style.width=state.st+'%';el('xpBar').style.width=Math.min(100,state.xp/state.req*100)+'%';el('hpTxt').textContent=Math.round(state.hp);el('stTxt').textContent=Math.round(state.st);el('xpTxt').textContent=state.xp+' / '+state.req;el('nameText').textContent=state.name;el('identityText').textContent=state.race;el('worldText').textContent=state.world;el('roleText').textContent=state.role;el('stageText').textContent=stage();el('levelText').textContent=state.level;el('xpText2').textContent=state.xp;el('reqText').textContent=state.req;el('strText').textContent=state.attrs.str;el('agiText').textContent=state.attrs.agi;el('vitText').textContent=state.attrs.vit;el('intText').textContent=state.attrs.int;el('perText').textContent=state.attrs.per;el('wilText').textContent=state.attrs.wil;el('titleText').textContent=state.title;el('authorityText').textContent=state.authority;el('deathText').textContent=state.deaths;el('weatherText').textContent=state.weather;el('memoryText').textContent=state.authority+' world changes';el('hiddenText').textContent=state.portalSeen?'PARTIAL SIGNAL':'UNKNOWN';el('coinText').textContent=state.coins;el('playerCount').textContent=Math.max(1,players.size+1);el('networkStatus').textContent=connected?'Supabase Realtime presence connected':'Local session';el('lootText').textContent=state.inventory.includes('Aether Shard')?'Rare dimensional signature acquired.':'No high-grade signature detected.';renderMissions();radar()}
function renderMissions(){const list=[['The Signal Beneath Aerion',state.portalSeen?'ACTIVE':'AVAILABLE','Find the ancient signal under the outpost.'],['The Night Hunt',state.weather!=='Clear'?'ACTIVE':'DORMANT','Roaming predators grow aggressive after dusk.'],['The Guardian That Remembers',boss&&boss.visible?'ACTIVE':'HIDDEN','A high-value encounter guards a forgotten chamber.'],['The Unstable Transfer Point',state.portalSeen&&!state.choiceDone?'ACTIVE':'HIDDEN','Rare routes can disappear permanently.'],['Echo From Another World',state.world==='Velis'?'ACTIVE':'UNKNOWN','Something followed you through the gate.']];el('missionList').innerHTML=list.map(x=>`<div class="mission"><b>${x[0]}</b><span class="tag">${x[1]}</span><p>${x[2]}</p></div>`).join('');el('choiceArea').innerHTML=state.choiceDone?'<span class="ok">A choice has changed this world.</span>':'<button id="rareChoice">TRIGGER RARE DECISION</button>';el('rareChoice')?.addEventListener('click',rareChoice)}
function rareChoice(){el('choiceArea').innerHTML='<div class="box"><div class="eyebrow">RARE DECISION EVENT</div><p>A sealed shard hums inside a ruined altar. Take it, leave it, or destroy it. One option may never return.</p><button data-choice="TAKE">TAKE</button><button data-choice="LEAVE">LEAVE</button><button data-choice="DESTROY">DESTROY</button></div>';document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>choice(b.dataset.choice))}
function choice(c){state.choiceDone=true;state.authority++;if(c==='TAKE'){state.inventory.push('Aether Shard');state.portalSeen=true;state.title='Shard-Bearer';toast('The shard opened a route beneath Aerion.')}else if(c==='LEAVE'){state.portalSeen=true;state.title='Silent Witness';toast('The opportunity remains, but not forever.')}else{state.title='Pathbreaker';state.role='Breaker';toast('The route is gone. Permanently.')}save();ui()}
function openModal(id){document.querySelectorAll('.modal').forEach(m=>m.classList.remove('show'));el(id).classList.add('show');ui()}
function closeModal(){document.querySelectorAll('.modal').forEach(m=>m.classList.remove('show'))}
window.openModal=openModal;window.closeModals=closeModal;
document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openModal(b.dataset.open));document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeModal);
function mat(c,rough=.75,metal=.08){return new THREE.MeshStandardMaterial({color:c,roughness:rough,metalness:metal})}
function box(parent,x,y,z,s,c){const m=new THREE.Mesh(new THREE.BoxGeometry(...s),mat(c));m.position.set(x,y,z);parent.add(m);return m}
function cyl(parent,x,y,z,r,h,c,radial=8){const m=new THREE.Mesh(new THREE.CapsuleGeometry(r,h*.45,4,radial),mat(c));m.position.set(x,y,z);parent.add(m);return m}
function makeHumanoid(color,detail){const g=new THREE.Group();const torso=box(g,0,1.45,0,[.8,1.05,.48],color);const chest=box(g,0,1.8,0,[.95,.45,.55],detail);const head=new THREE.Mesh(new THREE.SphereGeometry(.34,16,12),mat(color));head.position.y=2.38;g.add(head);box(g,-.43,1.48,0,[.18,.85,.18],detail);box(g,.43,1.48,0,[.18,.85,.18],detail);box(g,-.22,.58,0,[.22,.95,.22],color);box(g,.22,.58,0,[.22,.95,.22],color);const sword=box(g,.72,1.05,.02,[.08,1.2,.12],0xd8e5ef);sword.rotation.z=-.25;return {g,head,torso,sword}}
function makeEnemy(x,z,kind='stalker'){const c=kind==='guardian'?0x8f365b:0x713849;const d=kind==='guardian'?0xffaf65:0xc04b68;const h=makeHumanoid(c,d);h.g.scale.setScalar(kind==='guardian'?1.45:1);h.g.position.set(x,0,z);h.g.userData={hp:kind==='guardian'?350:70,maxHp:kind==='guardian'?350:70,kind};scene.add(h.g);enemies.push(h.g);return h.g}
function terrain(){const geo=new THREE.PlaneGeometry(80,80,32,32);const p=geo.attributes.position;for(let i=0;i<p.count;i++){const x=p.getX(i),z=p.getY(i);p.setZ(i,Math.sin(x*.15)*.8+Math.cos(z*.12)*.7+Math.sin((x+z)*.05)*1.1)}geo.rotateX(-Math.PI/2);const m=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color:state.world==='Aerion'?0x1d3440:0x341b28,roughness:1}));scene.add(m)}
function tree(x,z,s=1){const g=new THREE.Group();g.position.set(x,0,z);box(g,0,1.6,0,[.35,3.2,.35],0x35281f);const c=new THREE.Mesh(new THREE.ConeGeometry(1.3*s,3.1*s,8),mat(0x183f38));c.position.y=3.7*s;g.add(c);const c2=c.clone();c2.scale.set(.72,.72,.72);c2.position.y=5.3*s;g.add(c2);scene.add(g)}
function crystal(x,z,c){const m=new THREE.Mesh(new THREE.OctahedronGeometry(.75,0),mat(c,.45,.25));m.position.set(x,1,z);m.rotation.set(.3,.6,.2);scene.add(m);return m}
function gate(x,z){const g=new THREE.Group();g.position.set(x,0,z);box(g,-2,2,0,[.55,4,.55],0x59616d);box(g,2,2,0,[.55,4,.55],0x59616d);box(g,0,3.85,0,[4.55,.55,.55],0x59616d);const ring=new THREE.Mesh(new THREE.TorusGeometry(1.45,.12,10,32),mat(0xffc76a,.35,.5));ring.rotation.x=Math.PI/2;ring.position.y=2;g.add(ring);scene.add(g);return g}
function build(){scene=new THREE.Scene();scene.background=new THREE.Color(state.world==='Aerion'?0x06131c:0x18070f);scene.fog=new THREE.Fog(state.world==='Aerion'?0x06131c:0x18070f,22,88);scene.add(new THREE.HemisphereLight(0xa9c8ff,0x172026,1.35));const sun=new THREE.DirectionalLight(0xfff3dc,2.2);sun.position.set(15,24,8);scene.add(sun);terrain();
for(let i=-30;i<=30;i+=6){tree(i,-18+Math.sin(i)*4,.9);tree(i,18+Math.cos(i)*3,.8)}
for(let i=0;i<10;i++){const a=i*Math.PI*2/10;crystal(Math.cos(a)*15,Math.sin(a)*15,i%2?0x6b74ff:0x50e6db)}
box(scene,-10,1,-10,[7,2.2,5],0x2a3b4c);box(scene,-1,1,-12,[4,2.2,3],0x243342);gate(13,12);portal=crystal(13,12,0xffce69);portal.scale.setScalar(.9);heroRoot=new THREE.Group();const h=makeHumanoid(0x3a8bd1,0x67e8ff);hero=h.g;heroRoot.add(hero);heroRoot.position.set(0,0,6);scene.add(heroRoot);makeEnemy(5,-10);makeEnemy(10,-8);makeEnemy(-12,7);makeEnemy(16,0);boss=makeEnemy(-16,-13,'guardian');if(!state.portalSeen)boss.visible=true;camera=new THREE.PerspectiveCamera(62,innerWidth/innerHeight,.1,200);camera.position.set(0,5.8,13);renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;el('world').innerHTML='';el('world').appendChild(renderer.domElement);addEventListener('resize',resize);resize()}
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)}
function attack(){if(!heroRoot)return;attackUntil=performance.now()+260;let target=null,bd=3.6;for(const e of enemies){if(!e.visible)continue;const d=e.position.distanceTo(heroRoot.position);if(d<bd){bd=d;target=e}}if(target){target.userData.hp-=10+state.attrs.str*1.8;toast('HIT · '+Math.round(10+state.attrs.str*1.8));if(target.userData.hp<=0){const isBoss=target.userData.kind==='guardian';if(isBoss){target.visible=false;state.authority+=3;state.title='Guardian-Breaker';state.portalSeen=true;xp(300);toast('GUARDIAN DEFEATED')}else{state.kills++;xp(30);target.position.set((Math.random()-.5)*50,.0,(Math.random()-.5)*50);target.userData.hp=target.userData.maxHp}}save();ui()}}
function interact(){if(!heroRoot)return;let best=null,bd=3.2;for(const o of scene.children){if(o===heroRoot)continue;if(!o.position)continue;const d=o.position.distanceTo(heroRoot.position);if(d<bd&&(o===portal||o.userData?.interactable)){best=o;bd=d}}if(Math.abs(heroRoot.position.x-13)<4&&Math.abs(heroRoot.position.z-12)<4){state.portalSeen=true;openModal('missions');toast('TRANSFER POINT DISCOVERED')}else{toast('The world notices your presence.')}save();ui()}
function ai(dt){for(const e of enemies){if(!e.visible)continue;const d=e.position.distanceTo(heroRoot.position);if(d<14){const v=new THREE.Vector3().subVectors(heroRoot.position,e.position).normalize();e.position.addScaledVector(v,dt*(e.userData.kind==='guardian'?1.1:.8));e.lookAt(heroRoot.position.x,1,e.position.z);if(d<1.6&&Math.random()<dt*.8){state.hp=Math.max(0,state.hp-(e.userData.kind==='guardian'?10:4));if(state.hp<=0){state.deaths++;state.hp=100;heroRoot.position.set(0,0,6);toast('YOU FELL · THE WORLD REMEMBERS')}}}}
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05);const dir=new THREE.Vector3((keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),0,(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0));const moving=dir.lengthSq()>0;if(moving){dir.normalize();const sp=(sprinting||keys.has('shift'))?7.4:4.5;heroRoot.position.addScaledVector(dir,dt*sp);heroRoot.rotation.y=Math.atan2(dir.x,dir.z);walkTime+=dt*8;state.st=Math.max(0,state.st-dt*(sp>6?6:1.5))}else{state.st=Math.min(100,state.st+dt*4);walkTime+=dt*2}
const bob=moving?Math.sin(walkTime)*.06:Math.sin(walkTime)*.015;hero.position.y=bob;hero.children.filter((c,i)=>i>2&&c.geometry instanceof THREE.BoxGeometry).forEach((c,i)=>c.rotation.z=(i%2?-1:1)*Math.sin(walkTime)*.25);camera.position.x+=(heroRoot.position.x-camera.position.x)*.08;camera.position.z+=(heroRoot.position.z+11-camera.position.z)*.08;camera.lookAt(heroRoot.position.x,1.4,heroRoot.position.z);ai(dt);state.weather=(clock.elapsedTime%40>28?'Dusk':'Clear');renderer.render(scene,camera);ui()}
function radar(){const r=el('radar');r.innerHTML='';if(!heroRoot)return;const add=(o,cl,range=30)=>{const dx=(o.position.x-heroRoot.position.x)/range,dz=(o.position.z-heroRoot.position.z)/range;if(Math.abs(dx)>1.2||Math.abs(dz)>1.2)return;const d=document.createElement('i');d.className='dot '+cl;d.style.left=(50+dx*43)+'%';d.style.top=(50+dz*43)+'%';r.appendChild(d)};add(heroRoot,'player-dot');enemies.slice(0,12).forEach(e=>e.visible&&add(e,e.userData.kind==='guardian'?'boss-dot':'enemy-dot'));add(portal,'poi-dot')}
function connect(){channel.on('presence',{event:'sync'},()=>{players.clear();Object.entries(channel.presenceState()).forEach(([k,v])=>players.set(k,v));ui()}).on('presence',{event:'join'},()=>toast('ANOTHER TRAVELER ENTERED AERION')).on('presence',{event:'leave'},()=>ui()).subscribe(async s=>{connected=s==='SUBSCRIBED';if(connected)await channel.track({name:state.name,level:state.level,world:state.world});ui()})}
document.addEventListener('keydown',e=>{keys.add(e.key.toLowerCase());if(e.key==='Tab'){e.preventDefault();openModal('system')}if(e.key==='Escape')closeModal();if(e.key.toLowerCase()==='e')interact();if(e.key===' ')attack()});document.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));el('attackBtn')?.addEventListener('pointerdown',attack);el('sprintBtn')?.addEventListener('pointerdown',()=>sprinting=true);['pointerup','pointercancel','pointerleave'].forEach(ev=>el('sprintBtn')?.addEventListener(ev,()=>sprinting=false));document.querySelectorAll('.dpad [data-key]').forEach(b=>{const k=b.dataset.key;b.addEventListener('pointerdown',()=>keys.add(k));['pointerup','pointercancel','pointerleave'].forEach(ev=>b.addEventListener(ev,()=>keys.delete(k)))});el('continueBtn')?.addEventListener('click',()=>{el('startScreen').classList.remove('show');build();connect();save()});document.querySelectorAll('.choice-card').forEach(c=>c.onclick=()=>{document.querySelectorAll('.choice-card').forEach(x=>x.classList.remove('selected'));c.classList.add('selected');state.race=c.dataset.race});el('startBtn')?.addEventListener('click',()=>{const selected=document.querySelector('.choice-card.selected');if(!selected){toast('CHOOSE YOUR ORIGIN');return}state={...load(),race:selected.dataset.race,name:selected.dataset.race==='Human'?'Wanderer':selected.dataset.race==='Veyr'?'Echo-Touched':'Ironborn'};el('startScreen').classList.remove('show');build();connect();save()});el('upgradeBtn')?.addEventListener('click',()=>{if(state.coins<50){toast('NOT ENOUGH COINS');return}state.coins-=50;if(Math.random()>.45){state.attrs.str+=2;state.inventory.push('Aether Shard');toast('UPGRADE SUCCESS')}else toast('UPGRADE FAILED');save();ui()});el('consumeBtn')?.addEventListener('click',()=>{const i=state.inventory.findIndex(x=>x.startsWith('Field Ration'));if(i<0){toast('NO RATIONS');return}state.st=Math.min(100,state.st+35);toast('STAMINA RESTORED');save();ui()});
ui();
